{
 "title": "VPN",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "VPN Ingress Packet Drop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "SHKF",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Connection Name", "value": "ConnectionName" },
       { "text": "Remote IP", "value": "RemoteIP" }
      ],
      "metricDefinition": "Microsoft.Network/virtualNetworkGateways",
      "metricName": "TunnelIngressPacketDropTSMismatch",
      "resourceGroup": "{resourceGroupName}",
      "resourceName": "{resourceName}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "VPN Egress Packet Drop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "SHKF",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Connection Name", "value": "ConnectionName" },
       { "text": "Remote IP", "value": "RemoteIP" }
      ],
      "metricDefinition": "Microsoft.Network/virtualNetworkGateways",
      "metricName": "TunnelEgressPacketDropTSMismatch",
      "resourceGroup": "{resourceGroupName}",
      "resourceName": "{resourceName}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "VPN Total Ingress Bytes",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "SHKF",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Connection Name", "value": "ConnectionName" },
       { "text": "Remote IP", "value": "RemoteIP" }
      ],
      "metricDefinition": "Microsoft.Network/virtualNetworkGateways",
      "metricName": "TunnelIngressBytes",
      "resourceGroup": "{resourceGroupName}",
      "resourceName": "{resourceName}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "VPN Total Egress Bytes",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "SHKF",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Connection Name", "value": "ConnectionName" },
       { "text": "Remote IP", "value": "RemoteIP" }
      ],
      "metricDefinition": "Microsoft.Network/virtualNetworkGateways",
      "metricName": "TunnelEgressBytes",
      "resourceGroup": "{resourceGroupName}",
      "resourceName": "{resourceName}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  }
 ]
}